### ISSUE TITLE
USER STORY: Newsletter Signup Form

### ISSUE THREAD

**Issue by leec313** [leec313/Golf-Plus#44]
As a **user** I can **sign up to the newsletter** so that **I can receive updates and news from the site**

## Tasks

- [x] Create the model
- [x] Create the view
- [x] Create the form
- [x] Create the URL
- [x] Create the template
- [x] Create the JavaScript code so that the newsletter only pops up once per user based on the browser cookie
